easy_admin:
  entities:
    DifficultyLevel:
      class: App\Entity\DifficultyLevel
      list:
        fields:
          - { property: 'name', type: 'text' }
          - { property: 'notation_fr', type: 'text' }
          - { property: 'notation_de', type: 'text' }
          - { property: 'colour', css_class: 'level-color' }