easy_admin:
  entities:
    Lines:
      class: App\Entity\Lines
      form:
        fields:
          - { property: 'id' }
          - { property: 'name' }
          - { property: 'difficulties', type: 'entity', type_options: { class: 'App\Entity\DifficultyLevel', choice_label: 'name', expanded: true, multiple: true } }
      list:
        title: 'list'
        fields:
          - { property: 'id' }
          - { property: 'name' }
          - { property: 'difficulties', template: 'easy_admin/Lines/difficulties.html.twig' }
          - { property: 'feedbacks', template: 'easy_admin/Lines/feedback.html.twig' }